### PR TITLE
Update mintupdate-ro.po

### PR DESCRIPTION
**Pull request by DorianB2017**
I updated mintupdate-ro.po (for v.2017.11.23)

### CODE REVIEW

**Comment by NikoKrause** [comment]
Same. Translations are made here: https://translations.launchpad.net/linuxmint/latest/+lang/ro

**Comment by DorianB2017** [comment]
For NikoKrause.
So what?! I used Github to correct and translate the "mintupdate-ro.po" file.

**Comment by NikoKrause** [comment]
This is not going to be merged:
https://github.com/linuxmint/mint-translations/pull/2

**Comment by DorianB2017** [comment]
Please Clem accepts the translated and corrected "mintupdate-ro.po" file by me. Thank you so much for this. Thanks also for Linux Mint v. 18.3.

**Comment by clefebvre** [comment]
Hi @DorianB2017, thanks for contributing. This is the wrong place for translations though, they're imported from Launchpad so your changes would be overridden.

**Comment by NikoKrause** [comment]
My speech

**Pull request closed without merging**
